
project_id = "bjsxekgraxbfqzhbqjff"

[functions.enhanced-workflow-system]
verify_jwt = true

[functions.send-approval-email]
verify_jwt = true

[functions.insert-client]
verify_jwt = true

[functions.process-loan-application]
verify_jwt = true

[functions.loan-approval]
verify_jwt = true

[functions.calculate-repayment]
verify_jwt = true

[functions.send-notification]
verify_jwt = true

[functions.get_loan_workflow]
verify_jwt = true
